name: kitab2
description: "تطبيق لقراءة الكتب الإلكترونية وتقييمها ومراجعتها"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0' # تحديث ليتوافق مع نسخة Dart الحالية (3.9.0)

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  # Firebase core + الخدمات المستخدمة في المشروع (مصادقة + قاعدة بيانات سحابية)
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.17.0
  firebase_storage: ^11.7.0
  # قارئ PDF
  flutter_pdfview: ^1.2.7
  pdfx: ^2.6.0
  # عارض PDF يدعم الويب (Syncfusion)
  # تم تعليق الاعتماد على syncfusion_flutter_pdfviewer مؤقتاً بسبب تعارض intl
  # syncfusion_flutter_pdfviewer: ^28.2.7
  # قارئ EPUB (قد يحتاج تحديث/بديل لاحقاً حسب التوافق)
  epub_viewer: 0.2.5
  # EPUB parsing and in-app rendering
  # (removed experimental packages to keep dependency resolution stable)
  # للوصول إلى المسارات المحلية (مستخدم بالفعل في قارئ الكتب)
  path_provider: ^2.1.3
  # مشاركة الكتاب (مطلوبة لميزة المشاركة TODO)
  share_plus: ^10.0.0
  webview_flutter: ^4.13.0
  epubx: ^4.0.0
  # File picker for selecting PDF/EPUB from device
  file_picker: ^5.2.5
  http: ^1.2.1

  # (اختياري لاحقاً) للتنسيق الدولي للتواريخ والأرقام
  # intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    # مجلدات الموارد (أضف الملفات الفعلية لاحقاً داخل هذه المسارات)
    - assets/books/
    - assets/images/
    # تأكد من إنشاء هذه المجلدات وإضافة ملفات PDF و صور أغلفة الكتب
  # fonts مفرغة مؤقتاً حتى إضافة ملفات الخط فعلياً
  fonts: []
